Blog app - Integration specs for views and fix n+1 problems
gitbygaurav/Blog-App pull request #8
Opened 2023-04-11 11:08 UTC by gauravgangwarweb

### **Hi Cr👋**

![HelloNewYearGIF](https://user-images.githubusercontent.com/68365169/231141934-45300720-e851-42ac-97b4-2ce9d457b18a.gif)

_**We have done the following changes :-**_ 

- [x] We made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
- [x] We used Capybara to write integration tests for each view in the project.

Thanks 🍻

2023-04-11 13:16 UTC, franclobo reviewed
Hi @gauravgangwarweb and @belmeetmule, 

![terminator](https://user-images.githubusercontent.com/58642949/231174603-457e8ee6-ec34-4098-85f3-7be2661a77b7.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't include the screenshots of your app's logs before and after the fix in your PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-11 17:13 UTC, BertrandConxy requested changes
Hi Team, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️

- [ ] While you have done great job writing good tests, some of them are failing as you can see in the screenshot below 👇 
![image](https://user-images.githubusercontent.com/90222110/231236274-a4b5e169-dffa-4e0a-99a3-d90be6c79457.png)

Therefore, I would suggest that you correct them 

- [ ] Looking at your spec folder, I didn't find the features folder which is supposed to contain all the integration tests, I would suggest that you add the necessary tests as in project requirements and in an appropriate way (i.e: integration tests are supposed to be in the features folder and naming is somehow different from others) so, please look back at the project requirements and study materials to create good tests. The following tutorial will be very helpful, It was written by a Microverse alumni student. Here is the 👉 [Link](https://hackernoon.com/how-to-build-awesome-integration-tests-with-capybara-j9333y68)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 17:13 UTC, BertrandConxy commented on app/controllers/posts_controller.rb
> +    @post = @user.posts.new(author: @user, title: params[:post][:title], text: params[:post][:text])
- [ ] Good job so far 👏 As I have seen in your `posts_controller`, you have not yet solved the n+1 problem as you have not yet used the `includes` method. Currently, this is how your index action in the posts controller looks 👇 
![image](https://user-images.githubusercontent.com/90222110/231233674-8e4db86f-803b-4f7c-b8b8-14c349c7cea1.png)

As a HINT: in your index action, you should have line of code that looks like this 
```ruby
@posts = @user.posts.includes(:comments)
```
Where @user is the user with the ID stored in the params object

By doing this, you are solving the n+1 problem because user posts will be queried together with comments 😉 
so please implement that 👍

2023-04-11 17:13 UTC, BertrandConxy commented on config/environments/development.rb
> +    Bullet.add_footer    = true
- [ ] From the project requirements, It is said not to use the bullet gem or anything concerning  it but I can see that in your development and test environment configurations, you are enabling it. 
![image](https://user-images.githubusercontent.com/90222110/231234985-e818f551-36ff-4206-87b5-8647ebc7ce00.png)

I would suggest that you remove the above code concerning the Bullet gem in this file but also in the test.rb file because it is not right. In addition, they stopped me from running the tests. I was able to run them when I removed them 😃 🙏

2023-04-11 17:13 UTC, BertrandConxy commented on config/environments/test.rb
> +  end
- [ ] As I suggested in the above comment, please remove the codes concerning the bullet gem because It is not allowed as we find in the project requirements but also, they led to some errors when someone try to run migrations 🙏

2023-04-12 07:47 UTC, gauravgangwarweb commented
Hii @BertrandConxy 
Thanks for suggesting changes
I have implemented those

2023-04-12 08:37 UTC, elisha2kyakpo1 approved these changes
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well on the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 08:38 UTC, merged